name:                eurorack-metadata
version:             0.1.0.0
github:              "mlang/eurorack-metadata"
license:             BSD3
author:              "Mario Lang"
maintainer:          "mlang@blind.guru"
copyright:           "2018-2020 Mario Lang"

description:         Eurorack module metadata

dependencies:
- aeson
- async
- base >= 4.7 && < 5
- directory
- extra
- filepath
- lucid >= 2.9 && < 3
- text
- raw-strings-qq
- units >= 2.4 && <= 2.5
- units-defs >= 2.0 && <= 2.2
- yaml

executables:
  site:
    main: site.hs
    other-modules: Eurorack.Modules, Eurorack.Units
    dependencies:
    - bytestring
    - hakyll
