name:                eurorack-metadata
version:             0.1.0.0
github:              "mlang/eurorack-metadata"
license:             BSD3
author:              "Mario Lang"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/foobarion#readme>

dependencies:
- aeson
- async
- base >= 4.7 && < 5
- directory
- extra
- filepath
- lucid >= 2.9 && < 3
- text
- raw-strings-qq
- units >= 2.4 && <= 2.5
- units-defs >= 2.0 && <= 2.1
- yaml

library:
  source-dirs: src

executables:
  site:
    main: site.hs
    dependencies:
    - bytestring
    - hakyll
    - eurorack-metadata
